openapi: 3.0.3
info:
  title: Lesson Management API
  description: API for managing lessons, including login, register, and video generation.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /api/auth/register:
    post:
      summary: User registration
      description: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Email already exists

  /api/auth/login:
    post:
      summary: User login
      description: Authenticate user and return JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized

  /api/lessons:
    post:
      summary: Create a new lesson
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                title:
                  type: string
                file:
                  type: string
                  format: binary
              required: [userId, title, file]
      responses:
        '200':
          description: Lesson created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'

  /api/lessons/{id}:
    get:
      summary: Get lesson details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lesson details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'

  /api/lessons/{id}/generate-video:
    post:
      summary: Generate a video for a lesson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Video generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required: [email, password]

    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        fullName:
          type: string
        role:
          type: string
      required: [email, password, fullName]

    Lesson:
      type: object
      properties:
        id:
          type: integer
        createdBy:
          $ref: '#/components/schemas/User'
        title:
          type: string
        textContent:
          type: string
        language:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time

    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        password:
          type: string
        fullName:
          type: string
        phone:
          type: string
        role:
          type: string
        createdAt:
          type: string
          format: date-time

    Video:
      type: object
      properties:
        id:
          type: integer
        lesson:
          $ref: '#/components/schemas/Lesson'
        videoUrl:
          type: string
        format:
          type: string
        duration:
          type: number
        resolution:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
